upcase-week-2-models/config/routes.rb
Rails.application.routes.draw do
  # get "/decks" => "decks#index"
  # get "/decks/new" => "decks#new"
  # get "/decks/:id" => "decks#show", as: :deck
  # post "/decks" => "decks#create"
  # get "/decks/:id/edit" => "decks#edit"
  # patch "/decks/:id" => "decks#update"
  # delete "/decks/:id" => "decks#destroy"
root to: "homes#index"
  resources :decks do
    resources :cards, except: :index

  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

end

upcase-week-2-models/app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
end

upcase-week-2-models/app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
  belongs_to :user
end

upcase-week-2-models/app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks
end

upcase-week-2-models/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if cookies[:user_id]
      user_id = cookies.signed[:user_id]
      User.find_by_id(user_id)
    end
  end
  helper_method :current_user

  def sign_in user
    cookies.signed[:user_id] = user.id
  end

  def authenticate
    if !signed_in?
    redirect_to new_session_path
    end
  end

    def signed_in?
     current_user
    end
  helper_method :signed_in?
  end

upcase-week-2-models/app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def show
    @deck = find_deck
    @card = @deck.cards.find(params[:id])
  end

  def new
    @deck = find_deck
    @card = @deck.cards.new
  end

  def create
    @deck = find_deck
    @card = Card.new(front: params[:card][:front],
                     back: params[:card][:back],
                     deck: @deck)
    @card.save
    redirect_to @deck
  end

  def edit
    @deck = find_deck
    @card = find_card
  end
  def update
    @deck = find_deck
    @card = find_card
    @card.update(front: params[:card][:front],
                  back: params[:card][:back],
                  deck: @deck)
    redirect_to @deck
  end
  def destroy
    @deck = find_deck
    @card = find_card
    @card.destroy
    redirect_to @deck
  end
  end

  private

  def find_deck
    Deck.find(params[:deck_id])
  end
  def find_card
    Card.find(params[:id])
  end

upcase-week-2-models/app/controllers/decks_controller.rb
class DecksController < ApplicationController
before_filter :authenticate
  def index
    @decks = Deck.all
  end
  def show
    @deck = Deck.find(params[:id])
    @cards = @deck.cards
  end
  def new
    @deck = Deck.new
  end
  def create
    @deck = Deck.new(name: params[:deck][:name])
    @deck.save
    redirect_to @deck
  end
  def edit
    @deck = Deck.find(params[:id])
  end
  def update
    @deck = Deck.find(params[:id])
    @deck.update(name: params[:deck][:name])
    redirect_to @deck
  end
  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy
    redirect_to @deck
  end



end

upcase-week-2-models/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index

  end
end

upcase-week-2-models/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:session][:email])
    sign_in(user)
    cookies.signed[:user_id] = user.id
    redirect_to decks_path

  end
  def destroy
    cookies.delete(:user_id)
    redirect_to decks_path
  end
end

upcase-week-2-models/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @user = User.new
  end
  def create
    @user = User.new(email: params[:user][:email])
    @user.save
    sign_in @user
    redirect_to decks_path
  end
  end

upcase-week-2-models/app/helpers/application_helper.rb
module ApplicationHelper
end

upcase-week-2-models/app/views/cards/edit.html.erb
<%= form_for([@deck, @card]) do |f| %>
  <%= f.label :front %>
  <%= f.text_field :front %>
  <br>
  <%= f.label :back %>
  <%= f.text_field :back %>
  <br>
  <%= f.submit "Edit card" %>
<% end %>

upcase-week-2-models/app/views/cards/new.html.erb
<%= form_for([@deck, @card]) do |f| %>
  <%= f.label :front %>
  <%= f.text_field :front %>
  <br>
  <%= f.label :back %>
  <%= f.text_field :back %>
  <br>
  <%= f.submit "Create card" %>
<% end %>

upcase-week-2-models/app/views/cards/show.html.erb
<%= link_to "Cards", deck_cards_path %>

<h2><%= @card.back%></h2>

upcase-week-2-models/app/views/decks/edit.html.erb
<%= form_for(@deck) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit "Update deck" %>
<% end %>

upcase-week-2-models/app/views/decks/index.html.erb
<%= link_to "New deck", new_deck_path %>
<ul>
<% @decks.each do |deck| %>
    <br>
<li><%=link_to deck.name, deck%> <%=link_to "edit", edit_deck_path(deck) %> <%= link_to "delete", deck, method: :delete, confirm: "Are you sure?" %>
</li>
<% end %>
</ul>

upcase-week-2-models/app/views/decks/new.html.erb
<%= form_for(@deck) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit "Create deck" %>
<% end %>

upcase-week-2-models/app/views/decks/show.html.erb
<%= link_to "Decks", decks_path %>
<h2><%= @deck.name%></h2>
<%= link_to "New Card", new_deck_card_path(@deck) %>
<br>
<% @cards.each do |card|%>
  <br>
  <li><%= link_to card.front, [@deck, card] %> <%= link_to "edit", edit_deck_card_path(@deck, card) %> <%= link_to "delete", [@deck, card], method: :delete, confirm: "Are you sure?" %></li>
<%end%>

upcase-week-2-models/app/views/homes/index.html.erb
Welcome to the flashcard app.

upcase-week-2-models/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UpcaseWeek2Models</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  Welcome <%= current_user.email %>
  <%= link_to "signout", session_path, method: :delete %>
              <% else%>
  <%= link_to "signup", new_user_path %>
  <%= link_to "signin", new_session_path %>
<% end %>


<%= yield %>

</body>
</html>

upcase-week-2-models/app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.submit "Signup" %>
<% end %>